### ISSUE TITLE
Additional Datasets

### ISSUE THREAD

**Issue by AlyFear** [saylorsd/green-dream#38]
Steve, please add the datasets as point data in the Other Key Features section.  
https://data.wprdc.org/dataset/city-of-pittsburgh-property-tax-delinquency
https://data.wprdc.org/dataset/city-owned-property

**Comment by AlyFear** [comment]
Also add in the Borders and Infrastructure as basin outlines (no object color fill) with Basin ID
https://data.wprdc.org/dataset/allegheny-county-watershed-boundaries

**Comment by saylorsd** [comment]
tax delinquency: highlight parcels more than 1 year delinquent

**Comment by saylorsd** [comment]
city owned - boundary color

**Comment by saylorsd** [comment]
remove hydro lines and areas and add watershed layer

**Comment by saylorsd** [comment]
@AlyFear How should we handle coloring the watershed layer?  Should I just make it outlines and labels?

**Comment by AlyFear** [comment]
Yes, anything that isn’t black will do.  They don’t have to be blue either, since the floodzones are blue.  You can use any colors that don’t make the map muddy.

Alyson Fearon
Community Conservation Director
Allegheny Land Trust

416 Thorn Street  |  Sewickley, PA  |  15143
Office: 412.741.2750x204  |  Mobile: 314.556.4892

www.alleghenylandtrust.org<http://www.alleghenylandtrust.org/>
facebook<https://www.facebook.com/alleghenylandtrust> | flickr<https://www.flickr.com/photos/68211232@N02/albums> | instagram<https://instagram.com/alleghenylandtr/>
linkedin<http://www.linkedin.com/company/allegheny-land-trust> | pinterest<https://www.pinterest.com/AlleghenyLandTr/> | twitter<https://twitter.com/AlleghenyLandTr> | youtube<https://www.youtube.com/user/AlleghenyLandTrust/videos>
[ALTlogo_esig_small][accreditationseal_small]

**Comment by saylorsd** [comment]
@AlyFear i pushed these changes to staging, can you take a look and let me know if it's good to go.

i also have a fix for #3 (sewershed labels) on there as well

**Comment by AlyFear** [comment]
Watershed outlines can be brought down from a 2pt line to a 1.5 so they don't dominate the map. And then make the font Bold, because I didn't even realize the labels were there until I turned off the other boundary outlines.

Thank you for getting the City Owned and Tax Delinquent on there! I know I said go nuts with the colors, haha, but can we set those to like 50% transparency so I don't go blind looking at Homewood? (Like you did for Vacant Lots, where ever that setting is.)

I'd still be happy to have this published now and you fix those little things later, I know I'd be excited to push out the new data updates to bring some fresh attention.

**Comment by saylorsd** [comment]
@AlyFear I made some changes, take another look when you have the chance.

**Comment by AlyFear** [comment]
Oh yeah much better on the colors and fonts

Alyson Fearon
Community Conservation Director
Allegheny Land Trust

416 Thorn Street  |  Sewickley, PA  |  15143
Office: 412.741.2750x204  |  Mobile: 314.556.4892

www.alleghenylandtrust.org<http://www.alleghenylandtrust.org/>
facebook<https://www.facebook.com/alleghenylandtrust> | flickr<https://www.flickr.com/photos/68211232@N02/albums> | instagram<https://instagram.com/alleghenylandtr/>
linkedin<http://www.linkedin.com/company/allegheny-land-trust> | pinterest<https://www.pinterest.com/AlleghenyLandTr/> | twitter<https://twitter.com/AlleghenyLandTr> | youtube<https://www.youtube.com/user/AlleghenyLandTrust/videos>
[ALTlogo_esig_small][accreditationseal_small]
